In [1]:
import pandas as pd

In [2]:
# 数据文件参数
filename = 'E:\\NLP\\Python数据分析与挖掘实战\\chapter5\\demo\\data\\bankloan.xls'
data = pd.read_excel(filename)
# 切片，并转化为 numpy矩阵形式
# 取前 8 列数据
x = data.iloc[:,:8].as_matrix()
# 4行 8列
x_ = data.iloc[:4,:8]
print(x)
print(x_)
# data.columns[[2, 3, 4]]

[[ 41.         3.        17.       ...,   9.3       11.359392   5.008608]
 [ 27.         1.        10.       ...,  17.3        1.362202   4.000798]
 [ 40.         1.        15.       ...,   5.5        0.856075   2.168925]
 ..., 
 [ 33.         1.        15.       ...,   7.6        0.491264   1.940736]
 [ 45.         1.        19.       ...,   8.4        2.302608   4.165392]
 [ 37.         1.        12.       ...,  14.7        2.994684   3.473316]]
   年龄  教育  工龄  地址   收入   负债率      信用卡负债      其他负债
0  41   3  17  12  176   9.3  11.359392  5.008608
1  27   1  10   6   31  17.3   1.362202  4.000798
2  40   1  15  14   55   5.5   0.856075  2.168925
3  41   1  15  14  120   2.9   2.658720  0.821280


In [3]:
y_ = data.iloc[:4, 8]
print(y_)
# 取第 9 列数据
y = data.iloc[:, 8].as_matrix()
print(y)

0    1
1    0
2    0
3    0
Name: 违约, dtype: int64
[1 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 1 0 0 1 0 0 0 0 0 1 0 0 0 1 1 0 1 1 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 1 1 0 1 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 1 1 0 0 0 1 0 1 1 1 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0
 0 1 0 0 0 1 0 1 1 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 1 0 0
 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 1 0 1 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 1 0
 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 1 0 1 1 1 0 0 0 0 0 1 1
 0 0 0 0 0 1 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 1 0 1 1 0 0 0 0 1 0 0 0 1 0 0 0
 0 0 0 0 0 0 1 1 0 0 0 1 0 1 0 0 0 1 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1
 1 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 

In [4]:
# 逻辑回归
from sklearn.linear_model import LogisticRegression as LR
# 随机逻辑回归
from sklearn.linear_model import RandomizedLogisticRegression as RLR

In [5]:
# 建立随机逻辑回归模型，筛选变量
# 可以通过 selection_threshold 来设置阈值， 默认为 0.25
rlr = RLR()
# 训练模型
rlr.fit(x, y)
# 获取特征筛选结果，也可以通过 .scores_ 方法获取各个特征的分数
rlr.get_support()
print(u'通过随机逻辑回归模型筛选特征结束')
# data.columns[:8] -> 此处需要 列 保持一致
print(u'有效特征为: %s' % ','.join(data.columns[:8][rlr.get_support()]))
print(data.columns[:8])
# 获取各个特征的分数
print(rlr.scores_)

通过随机逻辑回归模型筛选特征结束
有效特征为: 工龄,地址,负债率,信用卡负债
Index(['年龄', '教育', '工龄', '地址', '收入', '负债率', '信用卡负债', '其他负债'], dtype='object')
[ 0.08   0.075  0.975  0.365  0.     0.985  0.585  0.035]


In [6]:
# 筛选好特征
x = data[data.columns[:8][rlr.get_support()]].as_matrix()
print(x)
# 建立逻辑回归模型
lr = LR()
# 用筛选后的特征数据来训练模型
lr.fit(x, y)
print(u'逻辑回归模型训练搞定')
print(u'模型的平均正确率为: %s' % lr.score(x, y))

[[ 17.        12.         9.3       11.359392]
 [ 10.         6.        17.3        1.362202]
 [ 15.        14.         5.5        0.856075]
 ..., 
 [ 15.         3.         7.6        0.491264]
 [ 19.        22.         8.4        2.302608]
 [ 12.        14.        14.7        2.994684]]
逻辑回归模型训练搞定
模型的平均正确率为: 0.814285714286
