### 模型输入
> p_199

In [1]:
import pandas as pd

In [2]:
# 数据文件
inputfile = 'E:\\NLP\\Python_Data_Analysis_And_Mining_Actual_Combat\\chapter9\\demo\data\\moment.csv'
outputfile_1 = 'E:\\NLP\\Python_Data_Analysis_And_Mining_Actual_Combat\\chapter9\\demo\\tmp\\cm_train_svm.csv'
outputfile_2 = 'E:\\NLP\\Python_Data_Analysis_And_Mining_Actual_Combat\\chapter9\\demo\\tmp\\cm_test_svm.csv'
# 读取数据，指定编码
data = pd.read_csv(inputfile, encoding = 'gbk')
# 转为矩阵方便处理
data = data.as_matrix()

In [3]:
# 引入随机函数
from numpy.random import shuffle
# 随机打乱数据
shuffle(data)
# 选取前80%为训练数据
data_train = data[:int(0.8*len(data)), :]
# 选取后20%为测试数据
data_test = data[int(0.8 * len(data)):, :]
print(type(data_train))

<class 'numpy.ndarray'>


### SVM(支持向量机)
> p_200

### 输入层

In [4]:
# 构造特征和标签
# 训练集
# 从 下标为 2 的位置开始截取，一直取到结尾(含头), 尾部只能取 负值
# 放大特征
print(data_train[:, 2:])
print('-' * 20)
x_train = data_train[:, 2:] * 30
print(x_train)
# 索引为 0 的列数据
y_train = data_train[:, 0].astype(int)
# 测试集
x_test = data_test[:, 2:] * 30
y_test = data_test[:, 0].astype(int)

[[ 0.52900119  0.49027027  0.26443159 ..., -0.00419519 -0.00357085
   0.00592027]
 [ 0.56781361  0.58540704  0.2516147  ..., -0.00343437 -0.00258571
   0.0054227 ]
 [ 0.56735922  0.50208265  0.18490267 ...,  0.00243368 -0.00520144
  -0.00512189]
 ..., 
 [ 0.54432264  0.52223984  0.26366696 ..., -0.00367885  0.00452595
  -0.00669789]
 [ 0.44343942  0.52585771  0.1894128  ..., -0.00646552 -0.00697062
   0.00908709]
 [ 0.61812279  0.53977945  0.27486656 ..., -0.0025752   0.0036275
   0.0142242 ]]
--------------------
[[ 15.87003582  14.70810819   7.93294776 ...,  -0.12585585  -0.1071255
    0.17760813]
 [ 17.03440839  17.56221132   7.54844103 ...,  -0.10303122  -0.07757142
    0.162681  ]
 [ 17.02077651  15.06247947   5.54708016 ...,   0.07301037  -0.15604332
   -0.1536567 ]
 ..., 
 [ 16.32967932  15.66719526   7.91000883 ...,  -0.11036553   0.13577844
   -0.20093685]
 [ 13.30318251  15.77573133   5.68238409 ...,  -0.19396572  -0.20911866
    0.27261282]
 [ 18.54368373  16.19338359   8.24

### 训练层

In [5]:
# 导入SVM(支持向量机)
from sklearn import svm
# 构建模型
model = svm.SVC()
# 训练数据
model.fit(x_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [6]:
# 用于保存训练模型的模块
# http://blog.csdn.net/coffee_cream/article/details/51754484
import pickle
# wb -> 以二进制格式打开一个文件只用于写入。如果该文件已存在则将其覆盖。如果该文件不存在，创建新文件
pickle.dump(model, open('./model/svm.model', 'wb'))
#  上面这句话保存模型或，下次就可以使用训练好的svm模型了
# model = pickle.load(open('./model/svm.model', 'rb))

### 输出层

In [7]:
# 导入输出相关的库，生成混淆矩阵
from sklearn import metrics
# 将训练标签和预测训练标签做混淆矩阵
cm_train = metrics.confusion_matrix(y_train, model.predict(x_train))
# 将测试标签和预测测试标签做混淆矩阵
cm_test = metrics.confusion_matrix(y_test, model.predict(x_test))

In [8]:
print(cm_train)
print(cm_test)
# 保存结果
pd.DataFrame(cm_train, index = range(1, 6), columns = range(1, 6)).to_csv(outputfile_1)
pd.DataFrame(cm_test, index = range(1, 6), columns = range(1, 6)).to_csv(outputfile_2)

[[38  0  1  0  0]
 [ 0 36  1  0  0]
 [ 0  0 62  0  0]
 [ 0  0  4 15  0]
 [ 0  1  0  1  3]]
[[11  1  0  0  0]
 [ 0  7  0  0  0]
 [ 1  0 15  0  0]
 [ 0  0  0  5  0]
 [ 0  1  0  0  0]]
