### 模型输入
> p_199

In [1]:
import pandas as pd

In [2]:
# 数据文件
inputfile = 'E:\\NLP\\Python_Data_Analysis_And_Mining_Actual_Combat\\chapter9\\demo\data\\moment.csv'
outputfile_1 = 'E:\\NLP\\Python_Data_Analysis_And_Mining_Actual_Combat\\chapter9\\demo\tmp\\cm_train_svm.csv'
outputfile_2 = 'E:\\NLP\\Python_Data_Analysis_And_Mining_Actual_Combat\\chapter9\\demo\tmp\\cm_test_svm.csv'
# 读取数据，指定编码
data = pd.read_csv(inputfile, encoding = 'gbk')
# 转为矩阵方便处理
data = data.as_matrix()

In [3]:
# 引入随机函数
from numpy.random import shuffle
# 随机打乱数据
shuffle(data)
# 选取前80%为训练数据
data_train = data[:int(0.8*len(data)), :]
# 选取后20%为测试数据
data_test = data[int(0.8 * len(data)):, :]
print(type(data_train))

<class 'numpy.ndarray'>


### SVM(支持向量机)
> p_200

### 输入层

In [4]:
# 构造特征和标签
# 训练集
# 从 下标为 2 的位置开始截取，一直取到结尾(含头), 尾部只能取 负值
# 放大特征
print(data_train[:, 2:])
print('-' * 20)
x_train = data_train[:, 2:] * 30
print(x_train)
# 索引为 0 的列数据
y_train = data_train[:, 0].astype(int)
# 测试集
x_test = data_test[:, 2:] * 30
y_test = data_test[:, 0].astype(int)

[[ 0.54337925  0.52561898  0.15950954 ...,  0.00387242  0.00353983
  -0.0075266 ]
 [ 0.57591893  0.53589556  0.2332674  ...,  0.00341081 -0.00267705
  -0.00406101]
 [ 0.50888782  0.47326771  0.22443474 ..., -0.00456595 -0.00408252
  -0.00588582]
 ..., 
 [ 0.57487405  0.5618488   0.2565331  ..., -0.00244242  0.00261172
   0.00516869]
 [ 0.6386056   0.61926032  0.31971145 ..., -0.00487442  0.00308348
  -0.00449866]
 [ 0.55441777  0.54446335  0.24581289 ..., -0.00327961 -0.00352313
  -0.00631565]]
--------------------
[[ 16.30137759  15.7685694    4.78528632 ...,   0.11617251   0.10619496
   -0.225798  ]
 [ 17.27756793  16.07686674   6.99802212 ...,   0.10232439  -0.08031162
   -0.12183036]
 [ 15.26663475  14.19803133   6.73304232 ...,  -0.13697856  -0.12247548
   -0.17657466]
 ..., 
 [ 17.24622153  16.855464     7.69599291 ...,  -0.07327272   0.07835169
    0.15506073]
 [ 19.15816788  18.57780957   9.59134341 ...,  -0.14623248   0.09250428
   -0.1349598 ]
 [ 16.63253313  16.33390038   7.

### 训练层

In [5]:
# 导入SVM(支持向量机)
from sklearn import svm
# 构建模型
model = svm.SVC()
# 训练数据
model.fit(x_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [6]:
# 用于保存训练模型的模块
# http://blog.csdn.net/coffee_cream/article/details/51754484
import pickle
# wb -> 以二进制格式打开一个文件只用于写入。如果该文件已存在则将其覆盖。如果该文件不存在，创建新文件
pickle.dump(model, open('./model/svm.model', 'wb'))
#  上面这句话保存模型或，下次就可以使用训练好的svm模型了
# model = pickle.load(open('./model/svm.model', 'rb))

### 输出层

In [7]:
# 导入输出相关的库，生成混淆矩阵
from sklearn import metrics
# 将训练标签和预测训练标签做混淆矩阵
cm_train = metrics.confusion_matrix(y_train, model.predict(x_train))
# 将测试标签和预测测试标签做混淆矩阵
cm_test = metrics.confusion_matrix(y_test, model.predict(x_test))

In [9]:
print(cm_train)
print(cm_test)
# 保存结果
pd.DataFrame(cm_train, index = range(1, 6), columns = range(1, 6)).to_csv(outputfile_1)
pd.DataFrame(cm_test, index = range(1, 6), columns = range(1, 6)).to_csv(outputfile_2)

[[35  1  3  0  0]
 [ 0 32  0  0  0]
 [ 0  0 67  0  0]
 [ 0  0  3 17  0]
 [ 0  1  0  2  1]]
[[12  0  0  0  0]
 [ 0 12  0  0  0]
 [ 0  0 11  0  0]
 [ 0  0  1  3  0]
 [ 0  0  0  1  1]]


ValueError: No engine for filetype: 'csv'