In [1]:
import numpy as np

In [2]:
# 创建数组
a = np.array([1, 2, 3, 4, 5, 0])
print(a)

[1 2 3 4 5 0]


In [3]:
# 取前三个(切片)
print(a[:3])

[1 2 3]


In [5]:
# 当前数组的最小值
print(a.min())

0


In [6]:
# 从小到大排序，会对原始数据进行修改
a.sort()
print(a)

[0 1 2 3 4 5]


In [7]:
# 二维数组
b = np.array([[1, 2, 3], [4, 5, 6]])
# 各自平方
print(b * b)

[[ 1  4  9]
 [16 25 36]]
