In [1]:
import pandas as pd
# 导入随机函数shuffle，用来打散数据
from random import shuffle

In [3]:
# 数据信息
datafile = 'E:\\NLP\\Python数据分析与挖掘实战\\chapter6\\demo\\data\\model.xls'
# 读取数据（前三列特征，第四列是标签）
data = pd.read_excel(datafile)
# 将表格转换为矩阵
data = data.as_matrix()
print(data)
print('\n')
# 随机打乱数据
shuffle(data)
print(type(data))

[[4 1 1 1]
 [4 0 4 1]
 [2 1 1 1]
 ..., 
 [5 1 2 1]
 [2 1 0 0]
 [4 1 0 0]]


<class 'numpy.ndarray'>


### 数据划分
>### 随机选取20%作为测试集，剩下的80%作为训练集

In [ ]:
# 设置训练数据比例
p = 0.8
# 前 80% 为训练集
train = data[:int(len(data) * p), :]
# 后 20% 为测试集
test = data[int(len(data) * p):, :]